# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Theme configuration
# remote_theme: "mmistakes/so-simple-theme@3.2.0"
remote_theme: "L-E-A-P/so-leap-theme"
skin: "/assets/css/skins/dark.css"

# Site identity
locale: it
timezone: Europe/Rome
title: "LEAP"
description: "Laboratorio ElettroAcustico Permanente"
url: "https://www.leaphz.net"
baseurl: "" # the subpath of your site, e.g. "/blog"
logo: https://raw.githubusercontent.com/L-E-A-P/logo/main/2023-11-21-logo-web-sqare-key.png

# Content settings
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200

# MathJax configuration
mathjax:
  enable: true
  combo: "tex-svg"
  tags: "ams"

# Typography
google_fonts:
  - name: "Alegreya Sans"
    weights: "400,400i"
  - name: "Alegreya"
    weights: "400,400i"
  - name: "Ubuntu Mono"
    weights: "400,400i"

# Analytics & Comments
google_analytics: G-QZM89XVDCT
disqus:
  shortname: leap-2

# Social media
twitter:
  username: # site's Twitter username if you have one

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Feed
feed:
  path: atom.xml
  excerpt_only: true

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /saltati/:num/

# Search
search_full_content: true

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-target-blank

# Collections
collections:
  salti:
    output: true
    permalink: /:collection/:title/
  # saltati:  # Commentato - collezione vuota
  #   output: true
  #   permalink: /:collection/:title/
  archidipietra:
    output: true
    permalink: /:collection/:path/
  domeniche:
    output: true
    permalink: /:collection/:path/
  lazzaro:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Global defaults
  - scope:
      path: ""
    values:
      # image: https://raw.githubusercontent.com/L-E-A-P/logo/main/2023-11-21-logo-web-sqare-key.png // HERO HOME PAGE
      author: LEAP
      twitter:
        card: summary_large_image

  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
      author: LEAP
      show_date: true
      read_time: true

  # Lazzaro collection
  - scope:
      path: "_lazzaro"
      type: lazzaro
    values:
      layout: project
      comments: true
      share: true
      author: LEAP

  # Archi di pietra collection
  - scope:
      path: "_archidipietra"
      type: archidipietra
    values:
      layout: project
      comments: true
      share: true
      author: LEAP

  # Domeniche collection
  - scope:
      path: "_domeniche"
      type: domeniche
    values:
      layout: project
      comments: true
      share: true
      author: LEAP

  # Salti collection
  - scope:
      path: "_salti"
      type: salti
    values:
      layout: page
      comments: true
      share: true
      author: LEAP

  # Saltati collection - commentato (collezione vuota)
  # - scope:
  #     path: "_saltati"
  #     type: saltati
  #   values:
  #     layout: page
  #     comments: true
  #     share: true
  #     author: LEAP

# Site Author
author:
  name: LEAP
  picture: https://raw.githubusercontent.com/L-E-A-P/logo/main/2023-11-21-logo-web-sqare.png
  email: info@leaphz.net
  bio: "Laboratorio ElettroAcustico Permanente"
  location: "Roma, Italia"
  url: "https://www.leaphz.net"
  links:
    - title: Website
      url: https://www.leaphz.net
      icon: fas fa-link
    - title: GitHub
      url: https://github.com/l-e-a-p
      icon: fab fa-github
    - title: Telegram
      url: https://t.me/+T6f_6KIRNPszYTQ0
      icon: fab fa-telegram

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
  - title: Telegram
    url: https://t.me/+T6f_6KIRNPszYTQ0
    icon: fab fa-telegram
  - title: GitHub
    url: https://github.com/l-e-a-p
    icon: fab fa-github-square

# Social configuration for SEO
social:
  type: Organization
  name: LEAP - Laboratorio ElettroAcustico Permanente
  links:
    - https://www.leaphz.net
    - https://github.com/l-e-a-p
    - https://t.me/+T6f_6KIRNPszYTQ0

# SEO settings
lang: it
twitter:
  username: # Add if you get a Twitter account
  card: summary_large_image

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - leap-web.txt
  - README.md
  - LICENSE
  - TECHNICAL_REPORT.md
  - _config_production.yml.backup
  - "*.backup"
